Fix for exception
2025-06-20_08:44:20.047 [AWT-EventQueue-0] ERROR o.s.u.a.FindDicomActionListener - Cannot invoke "java.time.LocalDate.toString()" because "this.patientBirthDate" is null
java.lang.NullPointerException: Cannot invoke "java.time.LocalDate.toString()" because "this.patientBirthDate" is null
        at org.shanoir.ng.importer.model.Patient.toString(Patient.java:174)
        at org.shanoir.uploader.action.FindDicomActionListener.fillMediaWithPatients(FindDicomActionListener.java:221)