Fix tools.jackson.databind.exc.InvalidDefinitionException
tools.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.shanoir.ng.shared.event.ShanoirEvent`: cannot deserialize from Object value (no delegate- or property-based Creator): this appears to be a native image, in which case you may need to configure reflection for the class that is to be deserialized