Fix for JpaSystemException
org.springframework.orm.jpa.JpaSystemException: A collection with cascade="all-delete-orphan" was no longer referenced by the owning entity instance: org.shanoir.ng.subjectstudy.model.SubjectStudy.subjectStudyTags