Server fix for JpaSystemException: A collection with cascade="all-delete-orphan (to work with installed ShUp as well)
org.springframework.orm.jpa.JpaSystemException: A collection with cascade="all-delete-orphan" was no longer referenced by the owning entity instance: org.shanoir.ng.subjectstudy.model.SubjectStudy.subjectStudyTags